// Mocks generated by Mockito 5.4.6 from annotations
// in auksine_bycke/test/mock_database_helper.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:auksine_bycke/database/database_helper.dart' as _i3;
import 'package:auksine_bycke/utils/exercise_info.dart' as _i5;
import 'package:auksine_bycke/workouts/workout_models.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sqflite/sqflite.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDatabase_0 extends _i1.SmartFake implements _i2.Database {
  _FakeDatabase_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DatabaseHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseHelper extends _i1.Mock implements _i3.DatabaseHelper {
  MockDatabaseHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Database> get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _i4.Future<_i2.Database>.value(
              _FakeDatabase_0(this, Invocation.getter(#database)),
            ),
          )
          as _i4.Future<_i2.Database>);

  @override
  _i4.Future<_i5.ExerciseInfo?> getExerciseInfoById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getExerciseInfoById, [id]),
            returnValue: _i4.Future<_i5.ExerciseInfo?>.value(),
          )
          as _i4.Future<_i5.ExerciseInfo?>);

  @override
  _i4.Future<void> saveWorkout(_i6.WorkoutModel? workout) =>
      (super.noSuchMethod(
            Invocation.method(#saveWorkout, [workout]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i6.WorkoutModel>> getAllWorkouts() =>
      (super.noSuchMethod(
            Invocation.method(#getAllWorkouts, []),
            returnValue: _i4.Future<List<_i6.WorkoutModel>>.value(
              <_i6.WorkoutModel>[],
            ),
          )
          as _i4.Future<List<_i6.WorkoutModel>>);

  @override
  _i4.Future<List<String>> getExerciseReferenceIds() =>
      (super.noSuchMethod(
            Invocation.method(#getExerciseReferenceIds, []),
            returnValue: _i4.Future<List<String>>.value(<String>[]),
          )
          as _i4.Future<List<String>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getExerciseProgress(
    String? exerciseRefId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getExerciseProgress, [exerciseRefId]),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<double> getMaxWeightForExercise(String? exerciseRefId) =>
      (super.noSuchMethod(
            Invocation.method(#getMaxWeightForExercise, [exerciseRefId]),
            returnValue: _i4.Future<double>.value(0.0),
          )
          as _i4.Future<double>);
}
