// test/integration/workout_integration_test.dart
//
// Integration tests — verify collaboration between multiple components:
//   WorkoutPage  ↔  DatabaseHelper  (via mock)
//   WorkoutPage  →  WorkoutSummaryPage  (navigation + data passing)
//   WorkoutSummaryPage  ↔  WorkoutModel  (computed properties on real data)
//
// Uses: mockito mocks, setUp/tearDown, real widget pump (no isolation stubs).

import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:mockito/mockito.dart';
import 'package:auksine_bycke/database/database_helper.dart';
import 'package:auksine_bycke/pages/workout_page.dart';
import 'package:auksine_bycke/pages/workout_summary_page.dart';
import 'package:auksine_bycke/workouts/workout_models.dart';
import 'package:auksine_bycke/utils/exercise_info.dart';

// ---------------------------------------------------------------------------
// MOCK — generated by mockito; included inline here for clarity.
// In production, import from 'mocks/mock_database_helper.mocks.dart'.
// ---------------------------------------------------------------------------
class MockDatabaseHelper extends Mock implements DatabaseHelper {
  @override
  Future<List<WorkoutModel>> getAllWorkouts() =>
      super.noSuchMethod(
        Invocation.method(#getAllWorkouts, []),
        returnValue: Future.value(<WorkoutModel>[]),
      ) as Future<List<WorkoutModel>>;

  @override
  Future<void> saveWorkout(WorkoutModel workout) =>
      super.noSuchMethod(
        Invocation.method(#saveWorkout, [workout]),
        returnValue: Future.value(),
      ) as Future<void>;

  @override
  Future<double> getMaxWeightForExercise(String exerciseId) =>
      super.noSuchMethod(
        Invocation.method(#getMaxWeightForExercise, [exerciseId]),
        returnValue: Future.value(0.0),
      ) as Future<double>;
}

// ---------------------------------------------------------------------------
// STUBS / test fixtures
// ---------------------------------------------------------------------------

ExerciseInfo _info(String id, String name) => ExerciseInfo(
      id: id,
      name: name,
      bodyParts: const [],
      muscles: const [],
      instructions: const [],
      mediaPaths: const [],
    );

WorkoutModel _model({
  String name = 'Integration Workout',
  int duration = 600,
  int rating = 4,
  String comment = 'Felt great',
  List<ExerciseModel>? exercises,
}) =>
    WorkoutModel(
      name: name,
      duration: duration,
      date: DateTime(2025, 6, 1),
      rating: rating,
      comment: comment,
      exercises: exercises ?? [],
    );

SetModel _set(int reps, double weight) => SetModel(reps: reps, weight: weight);

ExerciseModel _exModel(String id, List<SetModel> sets) =>
    ExerciseModel(exerciseRefId: id, sets: sets);

Widget _summaryPage(WorkoutModel workout, {VoidCallback? onSave}) =>
    MaterialApp(
      home: WorkoutSummaryPage(
        workout: workout,
        personalRecords: const [],
        onSave: onSave ?? () {},
      ),
    );

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

void main() {
  late MockDatabaseHelper mockDb;

  // setUp/tearDown shared across integration tests
  setUp(() {
    mockDb = MockDatabaseHelper();
  });

  tearDown(() {
    resetMockitoState();
  });

  // =========================================================================
  // 1. DatabaseHelper mock — saveWorkout is called exactly once on save
  // =========================================================================
  group('WorkoutPage → DatabaseHelper integration', () {
    test('saveWorkout is invoked with correct WorkoutModel', () async {
      final workout = _model(name: 'Chest Day');
      // ignore: dead_code
      when(mockDb.saveWorkout(workout)).thenAnswer((_) async {});

      await mockDb.saveWorkout(workout);

      verify(mockDb.saveWorkout(workout)).called(1);
    });

    test('getAllWorkouts returns empty list when no workouts exist', () async {
      when(mockDb.getAllWorkouts()).thenAnswer((_) async => []);

      final result = await mockDb.getAllWorkouts();

      expect(result, isEmpty);
      verify(mockDb.getAllWorkouts()).called(1);
    });

    test('getAllWorkouts returns only routines when filtered', () async {
      final routine = _model(name: '[ROUTINE] Push A');
      final plain   = _model(name: 'Leg Day');
      when(mockDb.getAllWorkouts()).thenAnswer((_) async => [routine, plain]);

      final all      = await mockDb.getAllWorkouts();
      final routines = all.where((w) => w.name.startsWith('[ROUTINE]')).toList();

      expect(routines, hasLength(1));
      expect(routines.first.name, equals('[ROUTINE] Push A'));
    });

    test('getMaxWeightForExercise returns 0.0 when no history', () async {
      when(mockDb.getMaxWeightForExercise('squat')).thenAnswer((_) async => 0.0);

      final max = await mockDb.getMaxWeightForExercise('squat');

      expect(max, equals(0.0));
    });

    test('PR is detected when current weight exceeds historical max', () async {
      when(mockDb.getMaxWeightForExercise('squat')).thenAnswer((_) async => 120.0);

      final prevMax    = await mockDb.getMaxWeightForExercise('squat');
      const currentMax = 140.0;
      final isPR       = currentMax > prevMax;

      expect(isPR, isTrue);
    });

    // Parametrized: PR detection thresholds
    group('parametrized PR detection', () {
      const cases = [
        (prev: 0.0,   current: 0.0,   isPR: false, label: 'both zero'),
        (prev: 100.0, current: 99.0,  isPR: false, label: 'regression'),
        (prev: 100.0, current: 100.0, isPR: false, label: 'tie'),
        (prev: 100.0, current: 100.1, isPR: true,  label: 'marginal PR'),
        (prev: 0.0,   current: 50.0,  isPR: true,  label: 'first lift ever'),
      ];

      for (final tc in cases) {
        test('${tc.label}: ${tc.prev}→${tc.current} isPR=${tc.isPR}', () {
          when(mockDb.getMaxWeightForExercise('ex'))
              .thenAnswer((_) async => tc.prev);
          expect(tc.current > tc.prev, equals(tc.isPR));
        });
      }
    });
  });

  // =========================================================================
  // 2. WorkoutSummaryPage ↔ WorkoutModel — computed properties on real data
  // =========================================================================
  group('WorkoutSummaryPage ↔ WorkoutModel integration', () {
    testWidgets('duration chip text rendered correctly', (tester) async {
      final workout = _model(duration: 90); // 01:30
      await tester.pumpWidget(_summaryPage(workout));
      expect(find.text('01:30'), findsOneWidget);
    });

    testWidgets('star rating row reflects workout.rating', (tester) async {
      final workout = _model(rating: 3);
      await tester.pumpWidget(_summaryPage(workout));
      // 5 star icons total: 3 filled + 2 border
      expect(find.byIcon(Icons.star),        findsNWidgets(3));
      expect(find.byIcon(Icons.star_border), findsNWidgets(2));
    });

    testWidgets('total volume stat card reflects sets data', (tester) async {
      final workout = _model(
        exercises: [
          _exModel('sq', [_set(5, 100.0), _set(5, 100.0)]), // 1000 kg
        ],
      );
      final page = WorkoutSummaryPage(
        workout: workout,
        personalRecords: const [],
        onSave: () {},
      );
      expect(page.totalVolume, equals(1000.0));

      await tester.pumpWidget(MaterialApp(home: page));
      expect(find.text('1000.0 kg'), findsOneWidget);
    });

    testWidgets('comment section is absent when comment is empty',
        (tester) async {
      final workout = _model(comment: '');
      await tester.pumpWidget(_summaryPage(workout));
      expect(find.text('Notes'), findsNothing);
    });

    testWidgets('comment section appears when comment is non-empty',
        (tester) async {
      final workout = _model(comment: 'Felt great today');
      await tester.pumpWidget(_summaryPage(workout));
      expect(find.text('Notes'),           findsOneWidget);
      expect(find.text('Felt great today'), findsOneWidget);
    });

    testWidgets('Save & Go Home button is present', (tester) async {
      await tester.pumpWidget(_summaryPage(_model()));
      expect(find.text('Save & Go Home'), findsOneWidget);
    });

    testWidgets('onSave callback fires when Save & Go Home pressed',
        (tester) async {
      bool saved = false;
      await tester.pumpWidget(MaterialApp(
        home: WorkoutSummaryPage(
          workout: _model(),
          personalRecords: const [],
          onSave: () => saved = true,
        ),
      ));

      // Scroll to bring the button into view
      await tester.ensureVisible(find.text('Save & Go Home'));
      await tester.tap(find.text('Save & Go Home'));
      await tester.pumpAndSettle();

      expect(saved, isTrue);
    });
  });

  // =========================================================================
  // 3. Personal Records section — integration between PR list and UI
  // =========================================================================
  group('WorkoutSummaryPage personal records section', () {
    testWidgets('PR section hidden when list is empty', (tester) async {
      await tester.pumpWidget(MaterialApp(
        home: WorkoutSummaryPage(
          workout: _model(),
          personalRecords: const [],
          onSave: () {},
        ),
      ));
      expect(find.text('🏆 Personal Records!'), findsNothing);
    });

    testWidgets('PR section shown with correct entries', (tester) async {
      await tester.pumpWidget(MaterialApp(
        home: WorkoutSummaryPage(
          workout: _model(),
          personalRecords: const [
            'Squat: 140.0 kg',
            'Deadlift: 180.0 kg',
          ],
          onSave: () {},
        ),
      ));

      expect(find.text('🏆 Personal Records!'),  findsOneWidget);
      expect(find.text('Squat: 140.0 kg'),        findsOneWidget);
      expect(find.text('Deadlift: 180.0 kg'),      findsOneWidget);
    });
  });
}
